eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone:  http://localhost:8761/eureka
server:
  port: 8082
spring:
  application:
    name: monitoring
  config:
    import: optional:configserver:http://localhost:8888
prometheus:
  prometheusURL: http://prometheus-server.prometheus:9090
  alertingRules:
    ruleName: HighMemoryUsage
    expression: 'up{job="myjob"} == 0'

